language: node_js
node_js:
  - lts/carbon
env:
  global:
    - NPM_CONFIG_LOGLEVEL=warn
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
before_install:
    - npm install
script:
    - npm test
